---
- name: Manage users - creation + grants
  hosts: localhost

  tasks:
    - name: Create PostgreSQL user
      postgresql_user:
        login_host: "{{ server_fqdn }}"
        login_user: "{{ administrator_user }}"
        login_password: "{{ administrator_password }}"
        db: "{{ database_name }}"
        name: "{{ database_name }}_user"
        password: "{{ database_user_password }}"
        priv: "ALL"
        expires: "infinity"

    - name: Remove public role on databases
      postgresql_user:
        login_host: "{{ server_fqdn }}"
        login_user: "{{ administrator_user }}"
        login_password: "{{ administrator_password }}"
        db: "{{ database_name }}"
        name: "public"
        state: absent

## Step above is to fix CVE-2018-1058. 
## Description : https://wiki.postgresql.org/wiki/A_Guide_to_CVE-2018-1058%3A_Protect_Your_Search_Path#Do_not_allow_users_to_create_new_objects_in_the_public_schema
    - name: Remove CREATE on schema public - fix CVE-2018-1058
      postgresql_query:
        login_host: "{{ server_fqdn }}"
        login_user: "{{ administrator_user }}"
        login_password: "{{ administrator_password }}"
        db: "{{ database_name }}"
        query: REVOKE ALL ON SCHEMA public FROM public;

    - name: Create schema with the same name as the database
      postgresql_schema:
        login_host: "{{ server_fqdn }}"
        login_user: "{{ administrator_user }}"
        login_password: "{{ administrator_password }}"
        database: "{{ database_name }}"
        name: "{{ database_name }}"

    - name: Give all privileges to user on tables in schema
      postgresql_query:
        login_host: "{{ server_fqdn }}"
        login_user: "{{ administrator_user }}"
        login_password: "{{ administrator_password }}"
        db: "{{ database_name }}"
        #query: GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA {{ database_name }} TO {{ database_name }}_user;
        query: ALTER DEFAULT PRIVILEGES IN SCHEMA {{ database_name }} GRANT ALL PRIVILEGES ON TABLES TO {{ database_name }}_user;

    - name: Give all privileges to user on sequences in schema
      postgresql_query:
        login_host: "{{ server_fqdn }}"
        login_user: "{{ administrator_user }}"
        login_password: "{{ administrator_password }}"
        db: "{{ database_name }}"
        query: ALTER DEFAULT PRIVILEGES IN SCHEMA {{ database_name }} GRANT ALL PRIVILEGES ON SEQUENCES TO {{ database_name }}_user;

    - name: Give all privileges to user on functions in schema
      postgresql_query:
        login_host: "{{ server_fqdn }}"
        login_user: "{{ administrator_user }}"
        login_password: "{{ administrator_password }}"
        db: "{{ database_name }}"
        query: ALTER DEFAULT PRIVILEGES IN SCHEMA {{ database_name }} GRANT ALL PRIVILEGES ON FUNCTIONS TO {{ database_name }}_user;